### ISSUE TITLE
mb-solrquerywriter: directory?

### ISSUE THREAD

**Issue by jeffweeksio** [mineo/mb-solrquerywriter#3]
Mineo, sorry if this is the wrong way to go about this, but...

Does the mb-solrquerywriter need to be in a specific directory?  Following the instructions I'm not getting a file called solrwriter-0.0.1-SNAPSHOT-jar-with-dependencies.jar in the target folder.

**Comment by mineo** [comment]
Closing this because you've already email me about it and the error message looks like a very specific Maven problem and not something that's generally wrong with the code in this repository.
